### ISSUE TITLE
Image Configuration Bug

### ISSUE THREAD

**Issue by rossberenson** [frontenso/frontenso-11ty-starter#2]
Great starter for 11ty. I did a few updates for my setup that I'd love to share with you one day, when I have some time. I added globbing for scss and js so you don't need to manually add each component scss and js to the main files. 

When building and watching development, images are getting processed The below error shows in terminal. 

`Eleventy Error
[11ty] Benchmark    612ms  95%    27× (Configuration) "image" Nunjucks Shortcode`

I looked at the js for the image shortcode and it looks like the correct properties are being provided the the 11ty Image plugin. Are you coming across this error?

**Comment by einomi** [comment]
> Great starter for 11ty. I did a few updates for my setup that I'd love to share with you one day, when I have some time. I added globbing for scss and js so you don't need to manually add each component scss and js to the main files.

Thank you!

> When building and watching development, images are getting processed The below error shows in terminal.
>
> Eleventy Error [11ty] Benchmark    612ms  95%    27× (Configuration) "image" Nunjucks Shortcode
> 
> I looked at the js for the image shortcode and it looks like the correct properties are being provided the the 11ty Image plugin. Are you coming across this error?

Yes, I saw this error in the terminal too. I think it's related to the circumstance that generating images using `11ty-image` takes some time. So it's probably more like a warning than an error, if I get it right.

**Comment by rossberenson** [comment]
I also spent some time trying to add caching to images, so they don't need to be regenerated every time but nothing I tried was any faster. haha. Oh well. Having code to see if the image exists takes just as long as the build just creating the image variants.

**Comment by einomi** [comment]
I will try to find a way to optimise image generation. Because yeah, my team and I faced an issue before where the image generation took ages for pages with really big amounts of images.

**Comment by einomi** [comment]
Hi @rossberenson, I've updated `@11ty/eleventy-img` to the latest version and adjusted the configurations. The newest version in `master` now supports image generation on request only. As a result, during development, images will only be processed when the browser requests them. During the build process (when running `npm run build`), images will be processed as usual. This should help resolve the slow performance issue during development.
